<?php
$this->headTitle('Users');
?>
<div class="page-header">
	<h1>Users</h1>
</div>
<div class="row">
	<div class="col-lg-12" id="system-messages-container">
<?php echo $this->systemMessagesHtml($this->systemMessages); ?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'add'), 'default', true); ?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add user</a>
				</div>
			</div>
			<div class="panel-body">

				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
							<th class="text-center">Status</th>
							<th>ID</th>
                                                        <th>Category</th>
							<th>Title</th>
							<th>Date</th>
							<th>Author</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
<?php 
  foreach ($this->news as $individualNews) {
  if ($individualNews['status'] == Application_Model_DbTable_CmsNews::STATUS_DISABLED) {
  ?>
  <tr data-user-id="<?php echo $this->escape($individualNews['id']);?>" class="danger">
  <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
  <td><?php echo $this->escape($individualNews['title']);?></td>
  <td><?php echo $this->escape($individualNews['category']);?></td>
  <td><?php echo $this->escape($individualNews['date_posted']);?></td>
  <td><?php echo $this->escape($individualNews['author_id']);?></td>
  <td class="text-center">
  <div class="btn-group btn-group-sm" role="group" aria-label="...">
<a 
    target="_blank"
    href=""
    type="button" class="btn btn-default" title="preview">
    <i class="glyphicon glyphicon-eye-open"></i>
</a>
  <a
  href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'edit', 'id' => $individualNews['id']), 'default', true);?>"
  type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
  <button data-user-id="<?php echo $this->escape($individualNews['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
  <button data-user-id="<?php echo $this->escape($individualNews['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

  </div>
  </td>
  </tr>
  <?php
  } else {
  ?>
  <tr data-user-id="<?php echo $this->escape($individualNews['id']);?>">
  <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
  <td><?php echo $this->escape($individualNews['title']);?></td>
  <td><?php echo $this->escape($individualNews['category']);?></td>
  <td><?php echo $this->escape($individualNews['date_posted']);?></td>
  <td><?php echo $this->escape($individualNews['author_id']);?></td>
  <td class="text-center">
  <div class="btn-group btn-group-sm" role="group" aria-label="...">
<a 
  target="_blank"
  href=""
  type="button" class="btn btn-default" title="preview">
  <i class="glyphicon glyphicon-eye-open"></i>
</a>
  <a
  href="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'edit', 'id' => $individualNews['id']), 'default', true);?>"
  type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
  <button data-user-id="<?php echo $this->escape($individualNews['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disabled"><i class="glyphicon glyphicon-remove"></i></button>
  <button data-user-id="<?php echo $this->escape($individualNews['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
  

  </div>
  </td>
  </tr>
  <?php
  }
  ?>

  <?php
  }
 ?>

					</tbody>
				</table>



			</div>
		</div>
	</div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Delete user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"> </i>Delete</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Disable user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to disable user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"> </i> Disable</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_news', 'action' => 'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Enable user</h4>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to enable user?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Enable</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<div id="message-templates" style="display: none">
	<div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<span data-container="message-text"></span>
	</div>

	<div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<span data-container="message-text"></span>
	</div>

</div>