<?php 
date_default_timezone_set('GMT');
?>
<section class="bredcrumbs">

    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">News</a></li>
            </ol>
        </article>
    </div>
</section>
<main>
    <section class="news newsPage">
        <div class="container">
            <h3>NEWS</h3>
            <div class="row">

                <?php foreach($this->news as $individualNews) { ?>
                
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img width="330" height="186" class="img-responsive" src="<?php echo $this->newsImgUrl($individualNews) ? $this->newsImgUrl($individualNews) : "/front/img/news_car.jpg" ;?>" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>

                        <figcaption>
                            <a href="<?php echo $this->newsUrl($individualNews) ;?>"><h4><?php echo $individualNews['title'];?></h4></a>
                            <button type="button" class="btn items"><?php echo date('d F Y' , strtotime($individualNews['date_posted'])) ;?></button>
                            <button type="button" class="btn items">Add comment</button>
                            <p><?php echo substr(strip_tags($individualNews['body']), 0, 100) . "...";?></p>

                        </figcaption>
                    </figure>
                </div>
                
                <?php } ?>
                
<!--                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="/front/img/news_car1.jpg" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>
                        <figcaption>
                            <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                            <button type="button" class="btn items">25 April 2015</button>
                            <button type="button" class="btn items">Add comment</button>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                Volumus sensibus qui ex, eum duis doming ad.</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="/front/img/news_car1.jpg" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>
                        <figcaption>
                            <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                            <button type="button" class="btn items">25 April 2015</button>
                            <button type="button" class="btn items">Add comment</button>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                Volumus sensibus qui ex, eum duis doming ad.</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="/front/img/news_car.jpg" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>
                        <figcaption>
                            <a href="#"> <h4>READY FOR TRACK DAY</h4></a>
                            <button type="button" class="btn items">25 April 2015</button>
                            <button type="button" class="btn items">Add comment</button>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                Volumus sensibus qui ex, eum duis doming ad.</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="/front/img/news_car1.jpg" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>
                        <figcaption>
                            <a href="#"> <h4>READY FOR TRACK DAY</h4></a>
                            <button type="button" class="btn items">25 April 2015</button>
                            <button type="button" class="btn items">Add comment</button>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem regione ne ius.
                                Vis quis lobortis dissentias ex, in du aft philosophia, malis necessitatibus no mei. 
                                Volumus sensibus qui ex, eum duis doming ad.</p>
                        </figcaption>
                    </figure>
                </div>
                <div class="col-sm-6 col-md-4">
                    <figure class="newsItem">
                        <div class="imgNews">
                            <img class="img-responsive" src="/front/img/news_car.jpg" alt=""/>
                            <div class="hoverNews text-center">
                                <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>
                            </div>
                        </div>
                        <figcaption>
                            <a href="#"><h4>READY FOR TRACK DAY</h4></a>
                            <button type="button" class="btn items">25 April 2015</button>
                            <button type="button" class="btn items">Add comment</button>
                            <p>Ea ullum liber aperiri mi, impetus ate philosophia ad duo, quem</p>
                        </figcaption>
                    </figure>
                </div>-->


            </div>
        </div>
    </section>

</main>



