<?php
$this->headTitle('Catalogue');
?>
<div class="page-header">
    <h1>Catalogue</h1>
</div>
<div class="row">
    <div class="col-lg-12" id="system-messages-container">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                  <button type="button" class="btn btn-default">Components</button>
                  <button type="button" class="btn btn-default">Configurations</button>
                   <button type="button" class="btn btn-default">Other</button>
                 </div>
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'add'), 'default', true); ?>"
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add catalogue</a>
                </div>
            </div>
            <div class="panel-body">

                <table id="table-rows" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Status</th>
                            <th>ID</th>
                            <th>Category</th>
                            <th>Title</th>
                            <th>Date</th>
                            <th>Author</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
//                        var_dump($this->catalogue);
                        foreach ($this->catalogue as $individualCatalogue) {
                            if ($individualCatalogue['status'] == Application_Model_DbTable_CmsCatalogue::STATUS_DISABLED) {
                                ?>
                                <tr data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>" class="danger">
                                    <td><?php echo $this->escape($individualCatalogue['id']); ?></td>
                                    <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                                    <td><?php echo $this->escape($individualCatalogue['id']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['category']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['title']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['date_posted']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['username']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a 
                                                target="_blank"
                                                href="<?php echo $this->catalogueUrl($individualCatalogue) ;?>"
                                                type="button" class="btn btn-default" title="preview">
                                                <i class="glyphicon glyphicon-eye-open"></i>
                                            </a>
                                            <a
                                                href="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'edit', 'id' => $individualCatalogue['id']), 'default', true); ?>"
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                            <button data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>

                                        </div>
                                    </td>
                                </tr>
                                <?php
                            } else {
                                ?>
                                <tr data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>">
                                    <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                                    <td><?php echo $this->escape($individualCatalogue['id']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['category']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['title']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['date_posted']); ?></td>
                                    <td><?php echo $this->escape($individualCatalogue['username']); ?></td>
                                    <td class="text-center">
                                        <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                            <a 
                                                target="_blank"
                                                href="<?php echo $this->catalogueUrl($individualCatalogue) ;?>"
                                                type="button" class="btn btn-default" title="preview">
                                                <i class="glyphicon glyphicon-eye-open"></i>
                                            </a>
                                            <a
                                                href="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'edit', 'id' => $individualCatalogue['id']), 'default', true); ?>"
                                                type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                            <button data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>" data-action="disable" type="button" class="btn btn-default" title="disabled"><i class="glyphicon glyphicon-remove"></i></button>
                                            <button data-catalogue-id="<?php echo $this->escape($individualCatalogue['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>


                                        </div>
                                    </td>
                                </tr>
                                <?php
                            }
                            ?>

                            <?php
                        }
                        ?>

                    </tbody>
                </table>



            </div>
        </div>
    </div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'delete'), 'default', true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Delete catalogue</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete catalogue?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"> </i>Delete</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'disable'), 'default', true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Disable catalogue</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to disable catalogue?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"> </i> Disable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<form method="post" action="<?php echo $this->url(array('controller' => 'admin_catalogue', 'action' => 'enable'), 'default', true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Enable catalogue</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to enable catalogue?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"> </i> Enable</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<div id="message-templates" style="display: none">
    <div data-container="message-box-success" class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>

    <div data-container="message-box-error" class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span data-container="message-text"></span>
    </div>

</div>
<script>
<?php $this->inlineScript()->captureStart(); ?>

    $('#table-rows').on('click', "[data-action='delete']", function (e) {
        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is("[data-action='delete']") ? $(this) : $(this).closest("[data-action='delete']");


        var catalogueId = target.attr('data-catalogue-id');
        var catalogueInfo = target.attr('data-catalogueInfo');
//        var catalogueId = target.data("catalogueId");
//        alert(catalogueId);
//        $('#delete-warning-dialog').find('[name = "id"]'). //alternativni nacini
        $('#delete-warning-dialog [name = "id"] ').val(catalogueId); //alternativni nacin
        $('#delete-catalogue').text(catalogueInfo);
        $('#delete-warning-dialog').modal('show');

    });

    $('#table-rows').on('click', "[data-action='disable']", function (e) {
        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is("[data-action='disable']") ? $(this) : $(this).closest("[data-action='disable']");
        var catalogueId = target.attr('data-catalogue-id');
        var catalogueInfo = target.attr('data-catalogueInfo');
//        var catalogueId = target.data("catalogueId");
//        alert(catalogueId);
//        $('#delete-warning-dialog').find('[name = "id"]'). //alternativni nacini
        $('#disable-warning-dialog [name = "id"] ').val(catalogueId) //alternativni nacin
        $('#disable-catalogue').text(catalogueInfo);
        $('#disable-warning-dialog').modal('show');

    });


    $('#table-rows').on('click', "[data-action='enable']", function (e) {
        e.preventDefault();
        e.stopPropagation();

        var target = $(this).is("[data-action='enable']") ? $(this) : $(this).closest("[data-action='enable']");
        var catalogueId = target.attr('data-catalogue-id');
        var catalogueInfo = target.attr('data-catalogueInfo');

//        alert(catalogueId);
//        $('#enable-warning-dialog').find('[name = "id"]'). //alternativni nacini
        $('#enable-warning-dialog [name = "id"] ').val(catalogueId) //alternativni nacin
        $('#enable-catalogue').text(catalogueInfo);
        $('#enable-warning-dialog').modal('show');

    });




<?php $this->inlineScript()->captureEnd(); ?>
</script>