<?php 
$sitemapPage = $this->sitemapPage;
$this->headTitle($this->escape($sitemapPage['title']));    
$this->headMeta()->appendName('description', $this->escape($sitemapPage['description']));
?>
<main>
<section class="bredcrumbs">

    <div class="container">
        <article>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                            <?php foreach ($this->breadcrumb AS $b) { ?>
                                <li><a href="<?php echo $this->sitemapPageUrl($b['id']); ?>"><?php echo $b['short_title']; ?></a></li>
                            <?php } ?>
                        </ol>
        </article>
    </div>
</section>


    
<div class="container">

    <div class="header-a">
        <?php echo $this->escape($sitemapPage['title']);?>
    </div>
    
    <p>
    <?php echo $sitemapPage['body'];?>
    </p>
    
</div>
</main>
