<?php
$form = new Application_Form_Admin_TypesAdd();
?>
<div class="page-header">
    <h1>Example page header <small>Subtext for header</small></h1>
</div>

<!--<div class="row">-->

<div class="col-md-12">
    <div class="panel with-nav-tabs panel-default">
        <div class="panel-heading">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab1default" data-toggle="tab">Product types</a></li>
                <li><a href="#tab2default" data-toggle="tab">Product characteristics</a></li>
            </ul>

            <div class="panel-body">
                <div class="tab-content">

                    <div class="tab-pane fade in active" id="tab1default">
                        <h1>Product type manage form</h1>
                        <div class="row">
                            <div class="col-md-1">
                                
                                <!-- PRODUCT TYPE FORM START -->
                                
                                <form method="post" name="type" action="<?php echo $this->url(array("controller" => "admin_managecategories", "action" => "producttypesdelete"), "default", true);?>">
                                    <div id="producttypes">
                                        
                                    </div>
                                    <div class="form-actions">
                                        <input type="hidden" name="task" value="typedelete">
                                        <button id="btndelete" type="submit" value="submit">Delete</button>
                                    </div>
                                </form>
                                
                                <form method="post" name="type" action="<?php echo $this->url(array("controller" => "admin_managecategories", "action" => "producttypesinsert"), "default", true);?>">
                                    <div class="form-actions">
                                        <input type="hidden" name="task" value="typeinsert">
                                        <input type="text" name="type" value="">
                                        <button id="btninsert" type="submit" value="submit">Submit</button>
                                        
                                    </div>
                                </form>
                                    
                                
                                <!-- PRODUCT TYPE FORM END -->
                                
                                
                            </div>

                            <div class="col-md-3">
                                
                                
                                
                                
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="tab2default">
                        <h1>Product characteristic manage form</h1>
                        <form>

                            <!-- PRODUCT CHARACTERISTICS FORM START -->

                            
                            
                            <!-- PRODUCT CHARACTERISTICS FORM END -->
                            
                        </form>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div>

<script>
<?php $this->inlineScript()->captureStart(); ?>

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypes'), 'default', true);?>'
    }).done(function (data) {
        $('#producttypes').html(data);
    }).fail(function () {
        alert("Error while loading dashboard product types.");
    });
    
    $('#btninsert').on('submit', function (e) {
            e.preventDefault(); //stop manual form submit

            $.ajax({
                    url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypesinsert'), 'default', true); ?>',
                    method: 'post',
                    data: {
                            task: 'typeinsert',
                            type: target.find('[name="type"]').val()
                    }

            }).done(function (data) {

            }).fail(function () {
                    //error in communication with server
                    alert('Error: Server returned error');

            }).always(function () {

            });
	});
        
        
        $('#btndelete').on('submit', function (e) {
            e.preventDefault(); //stop manual form submit

            $.ajax({
                    url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypesdelete'), 'default', true); ?>',
                    method: 'post',
                    data: {
                            task: 'typedelete',
                            type: target.find('[name="selecttypes"]').val()
                    }

            }).done(function (data) {

            }).fail(function () {
                    //error in communication with server
                    alert('Error: Server returned error');

            }).always(function () {

            });
	});
    
    
<?php $this->inlineScript()->captureEnd(); ?>
</script>