<?php
$form = new Application_Form_Admin_TypesAdd();
?>
<div class="page-header">
    <h1>Example page header <small>Subtext for header</small></h1>
</div>

<!--<div class="row">-->

<div class="col-md-12">
    <div class="panel with-nav-tabs panel-default">
        <div class="panel-heading">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab1default" data-toggle="tab">Product types</a></li>
                <li><a href="#tab2default" data-toggle="tab">Product characteristics</a></li>
            </ul>

            <div class="panel-body">
                <div class="tab-content">

                    <div class="tab-pane fade in active" id="tab1default">
                        <h1>Product type manage form</h1>
                        <div class="row">
                            <div class="col-md-2">
                                <label>Product types</label>
                                <div id="producttypes">

                                </div>
                                <div class="form-actions">
                                    <button id="btndeletetype" class="btn btn-default">Delete type</button>
                                </div>


                                <!-- PRODUCT TYPE FORM END -->                                


                            </div>

                            <div class="col-md-3">
                                <div class="form-actions">
                                    <label for="typeinput">Insert product type</label>
                                    <input id="typeinput" type="text" name="type" value="">
                                    <button  class="btn btn-default" id="btninsert"  value="submit">Insert type</button>
                                </div>



                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="tab2default">
                        <h1>Product characteristic manage form</h1>
                        <form>

                            <!-- PRODUCT CHARACTERISTICS FORM START -->



                            <!-- PRODUCT CHARACTERISTICS FORM END -->

                        </form>
                    </div>

                </div>
            </div>

        </div>

    </div>
</div>

<script>
<?php $this->inlineScript()->captureStart(); ?>

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypes'), 'default', true); ?>'
    }).done(function (data) {
        $('#producttypes').html(data);
    }).fail(function () {
        alert("Error while loading dashboard product types.");
    });


    $('#btninsert').on('click', function (e) {
        e.preventDefault(); //stop manual form submit

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypesinsert'), 'default', true); ?>',
            method: 'post',
            data: {
                task: 'typeinsert',
                type: $("#typeinput").val()
            }

        }).done(function (data) {

            $.ajax({
                url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypes'), 'default', true); ?>'
            }).done(function (data) {
                $('#producttypes').html(data);
                $("#typeinput").val('');
            }).fail(function () {
                //error in communication with server
                alert('Error: Server returned error');
            }).always(function () {

            });


        }).fail(function () {
            //error in communication with server 
            alert('Error: Server returned error');


        }).always(function () {

        });
    });



    $("#btndeletetype").on("click", function (e) {

        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypesdelete'), 'default', true); ?>',
            method: 'post',
            data: {
                task: 'typedelete',
                type: $("#selecttypes").val()
            }

        }).done(function (data) {
//                console.log(data.type);
            $.ajax({
                url: '<?php echo $this->url(array('controller' => 'admin_managecategories', 'action' => 'producttypes'), 'default', true); ?>'
            }).done(function (data) {
                $('#producttypes').html(data);
            }).fail(function () {
                //error in communication with server
                alert('Error: Server returned error');
            }).always(function () {

            });
        });
    });



    $("#typeinput").keyup(function (event) {
        if (event.keyCode == 13) {
            $("#btninsert").click();
        }
    });
    
    $( document ).on("dblclick", "selecttypes", function (event) {
            $("#btndeletetype").click();
    });



<?php $this->inlineScript()->captureEnd(); ?>
</script>