<section class="bredcrumbs">

    <div class="container">
        <article>
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li><a href="#">Catalog</a></li>
                <li><a href="#">Category</a></li>
            </ol>
        </article>
    </div>
</section>


<main>
    <section class="search">
        <div class="container">
            <form method="POST" >
                <div class="input-group">
                    <span class="input-group-addon"></span>
                    <input type="text" class="form-control" placeholder="Type here the name of spare parts, model car or VIN-code">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Find goods</button>
                    </span>
                </div>
            </form>
            <p>For example: <span>Сute cars parts </span> or <span> Cute-cute parts</span></p>
        </div>
    </section>

    <section class="container goods borderGoods">
        <div class="row">
            <div class="col-md-12 buttons">
                <div class="pull-left">

                    <button type="button" class="btn btn-primary down-arrow">All</button>
                    <button type="button" class="btn items sale">Sale 50%</button>
                    <button type="button" class="btn items">New</button>
                    <button type="button" class="btn items">Action</button>
                </div>
                <div class="pull-right page">

                    <p> Per page:</p>
                    <button type="button" class="btn">25</button>
                    <button type="button" class="btn btn-primary down-arrow">50</button>
                    <button type="button" class="btn">75</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <article class="row">
                    <div class="col-xs-12">
                        <aside class="options">
                            <h2>Options<span class="glyphicon glyphicon-menu-down"></span></h2>
                            <div class="showOption">
                                <article class="catalog">
                                    <h2>Catalog</h2>
                                    <div class="category">
                                        <h3>Categoty name <span>x</span></h3>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                        <h4 class="active">Sub-categoty  <span>x</span></h4>
                                        <h4>Sub-categoty <span>x</span></h4>
                                    </div>
                                </article>
                                <article class="type">
                                    <h2>Type</h2>
                                    <form role="form">
                                        <div class="form-group">
                                            <select class="form-control" id="sel1">
                                                <option value="" disabled selected>Select type</option>
                                                <option value="">1</option>
                                                <option value="">2</option>
                                                <option value="">3</option>
                                                <option value="">4</option>
                                            </select>
                                        </div>
                                    </form>
                                </article>
                                <article class="radioButtons">
                                    <h2>Radio buttons</h2>
                                    <form role="form">
                                        <div class="radio">
                                            <label><input type="radio" name="optradio">Hard</label>
                                        </div>
                                        <div class="radio">
                                            <label><input type="radio" name="optradio">Soft</label>
                                        </div>

                                    </form>
                                </article>
                                <article class="color">
                                    <h2>Color</h2>
                                    <h4><span class="lemon"></span> Lemon yellow</h4>
                                    <h4><span class="pink"></span> Pink kitty</h4>
                                </article>
                                <article class="checkboxGroup">
                                    <h2>Checkbox</h2>
                                    <form role="form">
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Regular</label>
                                        </div>
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Tuning</label>
                                        </div>
                                        <div class="checkbox">
                                            <label><input type="checkbox" value="">Exclusive</label>
                                        </div>

                                    </form>
                                </article>
                                <article class="rangeSlider clearfix">
                                    <h2>Range</h2>
                                    <div class="nstSlider" data-range_min="0" data-range_max="800" 
                                         data-cur_min="50"  data-cur_max="524">

                                        <div class="bar"></div>
                                        <div class="leftGrip"></div>
                                        <div class="rightGrip"></div>
                                    </div>
                                    <div class="leftLabel pull-left"></div>
                                    <div class="rightLabel pull-right"></div>
                                </article>
                            </div>
                        </aside>
                    </div>
                </article>
            </div>

            <div class="col-md-10">
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items2.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T-Rex®</h3></a>
                                <p>Billet Grilles</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#">
                                <img class="img-responsive" src="/front/img/items1.jpg" alt=""/>
                            </a>
                            <figcaption>
                                <a href="#"><h3>BedRug Bed Mat</h3></a>
                                <p>Bed Accessories</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items3.png" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>KW Suspensions®</h3></a>
                                <p>Suspension Systems </p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <article class="items center-block">

                        <figure>
                            <a href="#"><img class="img-responsive" src="/front/img/items4.jpg" alt=""/></a>
                            <figcaption>
                                <a href="#"> <h3>T5i®</h3></a>
                                <p>Spoilers & Wings</p>
                                <button type="button" class="btn">$54<sup>99</sup></button>
                            </figcaption>

                        </figure>
                    </article>
                </div>


                <div class="col-xs-12">
                    <nav  class="text-center" aria-label="Page navigation">
                        <ul class="pagination">
                            <li>
                                <a href="#" aria-label="Previous">
                                    <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Preview
                                </a>
                            </li>
                        </ul>
                        <ul class="pagination">
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a>...</a></li>
                            <li><a href="#">65</a></li>
                        </ul>
                        <ul class="pagination">
                            <li>

                                <a href="#" aria-label="Next">
                                    Next <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>


        </div>

    </section>
</main>