<?php 
/* Dve varijable koje su zaduzene za skrivanje elemenata layouta:
 * $this->dontShowInformation i $this->dontShowPrice
 * ujedno se nalazi i jQuery manipulacija redosleda section .getPrice i section. googleMap
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <?php echo $this->headTitle('CUBES Computer SHOP')->setSeparator(' | '); ?>
        <?php echo $this->headMeta()->appendName("description", "Hello world"); ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- @todo: fill with your company info or remove -->
        <?php echo $this->headMeta(); ?>
        <!-- General CSS -->

        <?php echo $this->headLink(); ?>
        <!-- Theme  CSS -->

        <?php echo $this->headStyle(); ?>

        <link rel="apple-touch-icon" href="<?php echo $this->baseUrl('/front/apple-touch-icon.png'); ?>">
        <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300,300italic,400italic,500,500italic,700,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <script src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyD5UMz1q-VLI2igjQT7a8_ADtDuRBxMMRQ'></script>
        <link href="<?php echo $this->baseUrl('/front/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/bootstrap.min.css'); ?>">
        <link href="<?php echo $this->baseUrl('/front/css/owl.carousel.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/starrr.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/jquery.nstSlider.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/main.css'); ?>">
        <link href="<?php echo $this->baseUrl('/front/css/responsive.css'); ?>" rel="stylesheet" type="text/css"/>

        <script src="<?php echo $this->baseUrl('/front/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js'); ?>"></script>

        <?php echo $this->headScript(); ?>
    </head>

    <!-- ======== @Region: body ======== -->
    <body>


        <header>
            <section>
                <div class="container">
                    <div class="header_top_in">
                        <ul class="list-unstyled list-inline">
                            <li>
                                <a href=""><img src="/front/img/location_icon.png" alt=""/>Location: <span>USA</span></a>
                            </li>
                            <li>
                                <a href=""><img src="/front/img/earth_icon.png" alt=""/>Language: <span>English</span></a>
                            </li>
                        </ul>
                        <ul  id="mid" class="list-unstyled list-inline">
                            <li>
                                <a href=""><img src="/front/img/phone_icon.png" alt=""/>1-800-987-0654 321</a>
                            </li>
                            <li>
                                <a href=""><img src="/front/img/car_icon.png" alt=""/>Nearest office: <span> SUNSET BLVD., BEVERLY HILLS, CA 90210</span></a>
                            </li>
                        </ul>
                        <ul class="list-unstyled list-inline">
                            <li>
                                <a href=""><img src="/front/img/sign_in_icon.png" alt="" /></a><a href="logIn.html"><span>Sign In </span></a> or <a href="registration.html"><span>Register</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>
            <section  class="navigation">
                <div class="container">
                    <article class="navigation-bar">
                        <nav class="navbar navbar-inverse">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span> 
                                </button>
                                <a class="navbar-brand" href="#"><img src="/front/img/logo_icon.png" alt=""/>Gear</a>
                            </div>
                            <div class="collapse navbar-collapse" id="myNavbar">
                                <?php echo $this->topMenuHtml();?>
<!--                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="/">Home</a></li>
                                    <li><a href="#myModal" data-toggle="modal" data-target="#myModal">Catalog</a></li>
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Payment & Delivery</a></li>
                                    <li><a href="#">News</a></li>
                                    <li><a href="#">Support</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>-->
                                <ul class="nav navbar-nav navbar-right">

                                    <li><a href="#" id="shopingCart"><img src="/front/img/cart_icon.png" alt=""/> Inbox <span class="badge">42</span></a></li>
                                </ul>
                            </div>
                        </nav>
                    </article>

                </div>
            </section>
        </header>
        <div class="shopingcart">
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <article class="">
                                <figure>
                                    <a href="#"><img class="img-responsive" src='http://placehold.it/100x100' alt=""></a>
                                </figure>
                                <div class="">
                                    <p class=""><a href="">Lorem ipsum</a></p>

                                </div>
                            </article>
                        </td>
                        <td>2835 DIN</td>
                        <td><a href="#" class="closeShop">X</a></td>
                    </tr>
                    <tr>
                        <td>
                            <article class="clearfix">
                                <figure>
                                    <a href="#"><img class="img-responsive" src='http://placehold.it/100x100' alt=""></a>
                                </figure>
                                <div class="historyProduct">
                                    <p class=""><a href="#">Lorem ipsum</a></p>
                                </div>
                            </article>
                        </td>
                        <td>2835 DIN</td>
                        <td><a href="#" class="closeShop">X</a></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>TOTAL: <span class="">5670 din</span></td>
                        <td colspan="2">
                            <a href="#l" class="btn btn-default" id="buy" >Buy</a>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <?php echo $this->layout()->content; ?>
        
        <?php if( !(isset($this->dontShowPrice) && $this->dontShowPrice == true)) { ?>
        <section class="getPrice">
        <div class="container">
            <div class="col-md-10 text-center">
                <h2>You want to know what else can our team? Well, download and see</h2>
            </div>
            <div class="col-md-2">
                <button class="btn btn-default" type="button">Get Price</button>
            </div>
        </div>
        </section>
        <?php } ?>
        
        <!--
        TODO: maybe put this in footer? Page product.html has this in the footer while most (all?) other
        have it in main element. By moving it, bottom JS code for reordering/appending would not be needed anymore...
        -->

        <?php if( !(isset($this->dontShowInformation) && $this->dontShowInformation == true) ) { ?>
        <section class="information">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-6">
                        <h3>Catalog</h3>
                        <div class="row">
                            <div class="col-md-4">
                                <p><a href="">Interior</a></p>
                                <p><a href="">Exterior</a></p>
                                <p><a href="">Performance</a></p>
                                <p><a href="">Lighting</a></p>
                            </div>
                            <div class="col-md-4">
                                <p><a href="">Wheels & Tires</a></p>
                                <p><a href="">Audio</a></p>
                                <p><a href="">Repair Parts</a></p>
                                <p><a href="">Body Parts</a></p>
                            </div>
                            <div class="col-md-4">
                                <p><a href="">RV Parts</a></p>
                                <p><a href="">Tools & Garage</a></p>
                                <p><a href="">Outdoor</a></p>
                            </div>
                        </div>

                    </div>
                    <div class=" col-md-3">
                        <h3>Delivery Information</h3>
                        <p><a href="">Delivery Information</a></p>
                        <p><a href="">Privacy policy</a></p>
                        <p><a href="">Terms & Condition</a></p>
                        <p><a href="">Contact us</a></p>

                    </div>
                    <div class=" col-md-3">
                        <h3>Our service</h3>
                        <p><a href="">My Account</a></p>
                        <p><a href="">Returns</a></p>
                        <p><a href="">Site map</a></p>
                    </div>
                </div>
            </div>
        </section>
        <?php } ?>

        <footer>
            <div class="container">
                <article class="navigation-bar">
                    <nav class="navbar navbar-inverse">

                        <div>
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="#">Home</a></li>
                                <li><a href="#">Catalog</a></li>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Payment & Delivery</a></li>
                                <li><a href="#">News</a></li>
                                <li><a href="#">Support</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right socialNetwork">
                                <li>
                                    <a href="#"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                                    <a href="#"><span class="fa fa-twitter" aria-hidden="true"></span></a>

                                </li>


                            </ul>
                        </div>
                    </nav>
                </article>

            </div>
            <section class="payments">
                <div class="container">
                    <div>
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="">
                                    <img src="/front/img/payPal.png" alt=""/>
                                </a> 
                                <a href="">
                                    <img src="/front/img/masterCard.png" alt=""/>
                                </a>
                                <a href="">
                                    <img src="/front/img/visa_icon.png" alt=""/>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="">Gear © 2016 All Rights Reserved</a>
                            </li>  


                        </ul>
                    </div>

                </div>
            </section>
            <section class="development ">
                <p class="text-center">Ovaj projekat je realizovan u okviru <a href="school.cubes.rs">CUBES SCHOOL</a>. Projekat realizovali: FRONTEND <a href="#">Ivan Trickovic</a>, BACKEND </p>
            </section>
        </footer>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a porttitor lectus. Quisque vitae bibendum mi,
                            eu malesuada lacus. Praesent placerat sodales massa, non sodales odio iaculis ac. Cras volutpat, justo vitae fringilla tincidunt,
                            nunc dolor vehicula nisl, ac aliquet tortor tellus vel ante. Maecenas euismod, ante in dictum gravida, magna leo porttitor sem,
                            eu posuere lorem ligula quis turpis. Nam eget aliquam erat, vel ornare odio. Curabitur vitae lorem volutpat, 
                            tristique augue eget, tincidunt lacus. Praesent in odio lorem. </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <!--Scripts -->
        <?php echo $this->inlineScript(); ?>
    


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/front/js/vendor/jquery-1.11.2.js'); ?>"><\/script>');</script>

    <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/front/js/owl.carousel.min.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/front/js/jquery.diyslider.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/front/js/jquery.nstSlider.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/front/js/jquery.validation.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl('/front/js/starrr.js" type="text/javascript'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/front/js/main.js'); ?>"></script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function (b, o, i, l, e, r) {
            b.GoogleAnalyticsObject = l;
            b[l] || (b[l] =
                    function () {
                        (b[l].q = b[l].q || []).push(arguments);
                    });
            b[l].l = +new Date;
            e = o.createElement(i);
            r = o.getElementsByTagName(i)[0];
            e.src = '//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e, r);
        }(window, document, 'script', 'ga'));
        ga('create', 'UA-XXXXX-X', 'auto');
        ga('send', 'pageview');
        
        
        //hack da bi se ispostovala pripadnost ovih elemenata u okviru main taga kao i njihov redosled
        
        if( $(".getPrice").length ) {
            if( $(".getPrice").length >= 2 ) {
                $(".getPrice").eq(1).appendTo( $("main") );
            } else {
                $(".getPrice").appendTo( $("main") );
            }
        }
        
        if( $(".information").length ) {
           $(".information").appendTo( $("main") );
        }
        
        if( $(".googleMap").length && !$(".location")) {
                $(".googleMap").detach().insertAfter(".getPrice");
        }
    </script>
</body>
</html>
