<?php 
$this->headTitle($this->sitemapPage["short_title"]); $this instanceof Zend_View;
?>
	<section class="bredcrumbs">

	    <div class="container">
		<article>
		    <ol class="breadcrumb">
			<li><a href="<?php echo $this->baseUrl('/');?>">Home</a></li>
                        <li><a href="<?php echo $this->url(array('controller' => 'info', 'action' => 'aboutus'));?>">About Us</a></li>
		    </ol>
		</article>
	    </div>
	</section>
<?php echo $this->sitemapPage['body'];?>

        <main>


