<?php 
$this->headTitle($this->sitemapPage["short_title"]);
$this->headMeta()->appendName("description", $this->sitemapPage['description']);
?>
<body>
<section class="bredcrumbs">

    <div class="container">
        <article>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                            <?php foreach ($this->breadcrumb AS $b) { ?>
                                <li><a href="<?php echo $this->sitemapPageUrl($b['id']); ?>"><?php echo $b['short_title']; ?></a></li>
                            <?php } ?>
                        </ol>
        </article>
    </div>
</section>
    <main class="contactUs">
        <section class="googleMap">
            <div class="mapWrapper">
                <div id='gmap_canvas' ></div>		  
            </div>
            <div class="formWrapp">
                <div class="formContact">
                    <h2>Contact Us</h2>
                    <div class="row">
                        <?php echo $this->sitemapPage['body'];?>
                    </div>
                    <form class="form-group">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Name" aria-label="...">
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Email" aria-label="...">
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                            <div class="col-xs-12">
                                <div class="input-group">
                                    <button class="btn btn-default formBtn" type="submit">Contact Us</button>
                                </div><!-- /input-group -->
                            </div>

                        </div><!-- /.row -->
                    </form>			    
                </div>
            </div>
        </section>
        <section class="location">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <p><i class="fa fa-map-marker" aria-hidden="true"></i>Choose another location:</p>
                    </div>
                    <div class="col-md-9">
                        <select id="locationStore" class="form-control">
                            <option value="1">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                            <option value="2">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                            <option value="3">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                        </select>

                    </div>
                </div>

            </div>
        </section>


    </main>