<body>
    <section class="bredcrumbs breadcrumbsPage">
        <div class="container">
            <article>
                <ol class="breadcrumb">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ol>
            </article>
        </div>
    </section>
    <main class="contactUs">
        <section class="googleMap">
            <div class="mapWrapper">
                <div id='gmap_canvas' ></div>		  
            </div>
            <div class="formWrapp">
                <div class="formContact">
                    <h2>Contact Us</h2>
                    <div class="row">
                        <div class="col-lg-6 contactImg text-center">
                            <img class="img-responsive" src="/front/img/contact.jpg" alt=""/>
                        </div>

                        <div class="col-lg-6">
                            <div class="adress">
                                <h3>1-800-987-0654 321</h3>
                                <p>SUNSET BLVD., BEVERLY HILLS, CA 90210</p>
                            </div>
                        </div>
                    </div>
                    <form class="form-group">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Name" aria-label="...">
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                            <div class="col-lg-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Email" aria-label="...">
                                </div><!-- /input-group -->
                            </div><!-- /.col-lg-6 -->
                            <div class="col-xs-12">
                                <div class="input-group">
                                    <button class="btn btn-default formBtn" type="submit">Contact Us</button>
                                </div><!-- /input-group -->
                            </div>

                        </div><!-- /.row -->
                    </form>			    
                </div>
            </div>
        </section>
        <section class="location">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <p><i class="fa fa-map-marker" aria-hidden="true"></i>Choose another location:</p>
                    </div>
                    <div class="col-md-9">
                        <select id="locationStore" class="form-control">
                            <option value="1">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                            <option value="2">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                            <option value="3">SUNSET BLVD., BEVERLY HILLS, CA 90210</option>
                        </select>

                    </div>
                </div>

            </div>
        </section>
        <section class="contact">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <p><img  src="/front/img/mail_icon.png" alt=""/><a href="mailto:exemple@yahoo.co.uk"> email@email.com</a></p>

                    </div>
                    <div class="col-md-4">
                        <p><img  src="/front/img/skype_icon.png" alt=""/><a href="#">gear.psdtemplate</a></p>
                    </div>
                    <div class="col-md-4">
                        <p><img  src="/front/img/phone_icon_1.png" alt=""/>1-800-987-0654 321</p>
                    </div>
                </div>
            </div>

        </section>

    </main>