<?php
$this->headTitle($this->sitemapPage['title']);
?>
<main>
<section class="bredcrumbs">

    <div class="container">
        <article>
                        <ol class="breadcrumb">
                            <li><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                            <?php foreach ($this->breadcrumb AS $b) { ?>
                                <li><a href="<?php echo $this->sitemapPageUrl($b['id']); ?>"><?php echo $b['short_title']; ?></a></li>
                            <?php } ?>
                        </ol>
        </article>
    </div>
</section>
    
    <section class="support">
        <div class="container">
            <div class="row">

                <div class="container">
                    <!-- About -->
                    <div class="row">
                        <div class="col-md-8">
                            <!-- About company -->
                            <div class="block">

                                <?php echo $this->sitemapPage['body']; ?>

                            </div>
                            <!-- The team -->

                            <!-- Quotes -->

                        </div>
                        <!-- sidebar -->
                        <div class="col-md-4 sidebar sidebar-right">
                            <div class="inner">
                                <?php if (!empty($this->sitemapPageChildLinks)) { ?>
                                    <div class="block">
                                        <h3 class="block-title sub-title">
                                            <span>Menu - <?php echo $this->escape($this->sitemapPage['short_title']);?></span>
                                        </h3>
                                        <!--<ul class="nav nav-list secondary-nav">--><ul class='list-group'>
                                            <?php foreach ($this->sitemapPageChildLinks as $childLink) { ?>
                                                <li class="list-group-item">
                                                    <a href="<?php echo $this->url(array('controller' => 'info', 'action' => 'support'), 'static-page-route-' . $childLink['id'], true); ?>"><i class="fa fa-chevron-right"></i> <?php echo $this->escape($childLink['short_title']); ?></a>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    </div>
                                <?php } ?>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
